"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import {
  Building2,
  CalendarDays,
  Check,
  ChevronDown,
  GraduationCap,
  Loader2,
  MapPin,
  Pencil,
  Plus,
  Search,
  ShieldCheck,
  Trash2,
  UserCheck,
  Users,
  UsersRound,
  X,
} from "lucide-react";
import InstitutionStudioShell from "@/components/InstitutionStudioShell";
import { institutionStudioApi } from "@/lib/institutionStudioApi";

type Section = "groups" | "events" | "people" | "campus";
const tabs: { id: Section; label: string; icon: any }[] = [
  { id: "groups", label: "Groups & Departments", icon: UsersRound },
  { id: "events", label: "Events & Opportunities", icon: CalendarDays },
  { id: "people", label: "Students & Faculty", icon: GraduationCap },
  { id: "campus", label: "Campus Places", icon: MapPin },
];

export default function StudioOperationsPage() {
  const [section, setSection] = useState<Section>("groups");
  const [bundle, setBundle] = useState<any>(null);
  const [departments, setDepartments] = useState<any[]>([]);
  const [staff, setStaff] = useState<any[]>([]);
  const [roles, setRoles] = useState<any[]>([]);
  const [events, setEvents] = useState<any[]>([]);
  const [approvals, setApprovals] = useState<any[]>([]);
  const [opportunities, setOpportunities] = useState<any[]>([]);
  const [places, setPlaces] = useState<any[]>([]);
  const [groups, setGroups] = useState<any[]>([]);
  const [busy, setBusy] = useState(true);
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");

  async function load() {
    setBusy(true);
    try {
      const [b,d,s,r,e,a,o,p,g] = await Promise.all([
        institutionStudioApi.bundle(),
        institutionStudioApi.departments().catch(() => []),
        institutionStudioApi.staff().catch(() => []),
        institutionStudioApi.roles().catch(() => []),
        institutionStudioApi.events().catch(() => []),
        institutionStudioApi.studentApprovals("pending").catch(() => []),
        institutionStudioApi.studioOpportunities().catch(() => []),
        institutionStudioApi.studioPlaces().catch(() => []),
        institutionStudioApi.studioGroups().catch(() => []),
      ]);
      setBundle(b); setDepartments(d || []); setStaff(s || []); setRoles(r || []); setEvents(e || []); setApprovals(a || []); setOpportunities(o || []); setPlaces(p || []); setGroups(g || []);
    } catch (e) { setNotice(e instanceof Error ? e.message : "Could not load institution operations."); }
    finally { setBusy(false); }
  }
  useEffect(() => { void load(); }, []);
  useEffect(() => {
    const applyHash = () => { const hash = window.location.hash.replace("#", "") as Section; if (tabs.some((t) => t.id === hash)) setSection(hash); };
    applyHash(); window.addEventListener("hashchange", applyHash); return () => window.removeEventListener("hashchange", applyHash);
  }, []);

  return <InstitutionStudioShell>
    <div className="space-y-5">
      <div><div className="text-sm font-bold uppercase tracking-[.15em] text-blue-600">Campus operations</div><h1 className="mt-2 text-3xl font-black tracking-tight">Manage Your Campus</h1><p className="mt-2 text-sm text-slate-500">Create and maintain the communities, people, events and physical campus that students see.</p></div>
      <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm"><div className="flex min-w-max gap-1">{tabs.map((tab) => { const Icon=tab.icon; const active=section===tab.id; return <button key={tab.id} onClick={() => { setSection(tab.id); window.history.replaceState(null,"",`#${tab.id}`); }} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${active?"bg-blue-600 text-white":"text-slate-600 hover:bg-slate-50"}`}><Icon className="h-4 w-4" />{tab.label}</button>; })}</div></div>
      {notice ? <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{notice}</div> : null}
      {busy ? <div className="grid min-h-72 place-items-center rounded-2xl border border-slate-200 bg-white"><Loader2 className="h-7 w-7 animate-spin text-blue-600" /></div> : null}
      {!busy && section === "groups" ? <GroupsDepartments groups={groups} departments={departments} reload={load} setNotice={setNotice} /> : null}
      {!busy && section === "events" ? <EventsOpportunities events={events} opportunities={opportunities} reload={load} setNotice={setNotice} /> : null}
      {!busy && section === "people" ? <People approvals={approvals} staff={staff} roles={roles} departments={departments} reload={load} setNotice={setNotice} /> : null}
      {!busy && section === "campus" ? <CampusPlaces places={places} reload={load} setNotice={setNotice} /> : null}
    </div>
  </InstitutionStudioShell>;
}

function GroupsDepartments({ groups, departments, reload, setNotice }: any) {
  const [group, setGroup] = useState({ name:"", description:"", category:"Official", visibility:"public", joinPolicy:"request", departmentId:"" });
  const [department, setDepartment] = useState({ name:"", code:"", description:"", active:true });
  const [search,setSearch]=useState("");
  const shown=groups.filter((g:any)=>`${g.name} ${g.category||""} ${g.studio_category||""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="grid gap-5 2xl:grid-cols-[1.45fr_.55fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-lg font-black">Campus Communities</h2><p className="mt-1 text-xs text-slate-500">Official groups are discovered only inside your institution profile.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search groups" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500" /></div></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs text-slate-500"><th className="pb-3 font-semibold">Group</th><th className="pb-3 font-semibold">Category</th><th className="pb-3 font-semibold">Members</th><th className="pb-3 font-semibold">Department</th><th className="pb-3 font-semibold">Featured</th><th className="pb-3"></th></tr></thead><tbody>{shown.map((g:any)=><tr key={g.id} className="border-b border-slate-50"><td className="py-3"><div className="font-bold">{g.name}</div><div className="mt-0.5 max-w-sm truncate text-xs text-slate-500">{g.description || "Official campus group"}</div></td><td className="py-3"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{g.studio_category||g.category||"Community"}</span></td><td className="py-3 font-semibold">{g.memberCount||0}</td><td className="py-3 text-slate-600">{departments.find((d:any)=>d.id===g.department_id)?.name||"—"}</td><td className="py-3"><button onClick={()=>void institutionStudioApi.updateStudioGroup(g.id,{featured:!g.featured}).then(reload)} className={`relative h-6 w-11 rounded-full ${g.featured?"bg-blue-600":"bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow ${g.featured?"left-6":"left-1"}`} /></button></td><td className="py-3 text-right"><select value={g.department_id||""} onChange={(e)=>void institutionStudioApi.updateStudioGroup(g.id,{departmentId:e.target.value||null}).then(reload)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs"><option value="">No department</option>{departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></td></tr>)}</tbody></table>{!shown.length?<Empty text="No groups found."/>:null}</div>
    </section>
    <div className="space-y-5"><FormCard title="Create Official Group" icon={UsersRound}><Field label="Group name" value={group.name} onChange={(v:any)=>setGroup({...group,name:v})}/><TextArea label="Description" value={group.description} onChange={(v:any)=>setGroup({...group,description:v})}/><div className="grid grid-cols-2 gap-3"><Field label="Category" value={group.category} onChange={(v:any)=>setGroup({...group,category:v})}/><Select label="Department" value={group.departmentId} onChange={(v:any)=>setGroup({...group,departmentId:v})} options={[{value:"",label:"None"},...departments.map((d:any)=>({value:d.id,label:d.name}))]}/></div><button disabled={!group.name} onClick={()=>void institutionStudioApi.createGroup({name:group.name,description:group.description,category:group.category,visibility:group.visibility,joinPolicy:group.joinPolicy}).then(async(created:any)=>{if(group.departmentId)await institutionStudioApi.updateStudioGroup(created.id,{departmentId:group.departmentId,studioCategory:group.category});setGroup({name:"",description:"",category:"Official",visibility:"public",joinPolicy:"request",departmentId:""});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4"/>Create group</button></FormCard>
      <FormCard title="Create Department" icon={Building2}><Field label="Department name" value={department.name} onChange={(v:any)=>setDepartment({...department,name:v})}/><Field label="Code" value={department.code} onChange={(v:any)=>setDepartment({...department,code:v})}/><TextArea label="Description" value={department.description} onChange={(v:any)=>setDepartment({...department,description:v})}/><button disabled={!department.name} onClick={()=>void institutionStudioApi.createDepartment(department).then(()=>{setDepartment({name:"",code:"",description:"",active:true});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4"/>Add department</button><div className="mt-4 space-y-2">{departments.map((d:any)=><div key={d.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><div className="text-sm font-bold">{d.name}</div><div className="text-xs text-slate-500">{d.code||"No code"}</div></div><button onClick={()=>void institutionStudioApi.updateDepartment(d.id,{name:d.name,code:d.code,description:d.description,active:!d.active}).then(reload)} className={`rounded-lg px-2 py-1 text-xs font-bold ${d.active?"bg-emerald-50 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{d.active?"Active":"Inactive"}</button></div>)}</div></FormCard></div>
  </div>;
}

function EventsOpportunities({ events, opportunities, reload, setNotice }: any) {
  const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,16);
  const later=new Date(Date.now()+90000000).toISOString().slice(0,16);
  const [event,setEvent]=useState<any>({title:"",description:"",location:"",startAt:tomorrow,endAt:later,visibility:"public",status:"published",rsvpEnabled:true});
  const [opp,setOpp]=useState<any>({kind:"internship",title:"",organization:"",description:"",location:"",applyUrl:"",deadline:""});
  return <div className="space-y-5">
    <div className="grid gap-5 2xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Events</h2><p className="mt-1 text-xs text-slate-500">Create, schedule, cancel and analyze RSVP-enabled campus events.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{events.map((e:any)=><div key={e.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${e.status==="published"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{e.status}</span><div className="mt-3 font-black">{e.title}</div><div className="mt-1 text-xs text-slate-500">{new Date(e.start_at).toLocaleString()} · {e.location||"Campus"}</div></div><CalendarDays className="h-5 w-5 text-blue-600"/></div><div className="mt-4 flex gap-2"><button onClick={()=>void institutionStudioApi.updateEvent(e.id,{title:e.title,description:e.description||"",location:e.location,startAt:e.start_at,endAt:e.end_at,capacity:e.capacity,visibility:e.visibility,status:e.status==="cancelled"?"published":"cancelled",imageUrl:e.image_url,rsvpEnabled:e.rsvp_enabled}).then(reload)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold">{e.status==="cancelled"?"Republish":"Cancel"}</button></div></div>)}{!events.length?<Empty text="No events yet."/>:null}</div></section>
      <FormCard title="Create Event" icon={CalendarDays}><Field label="Title" value={event.title} onChange={(v:any)=>setEvent({...event,title:v})}/><TextArea label="Description" value={event.description} onChange={(v:any)=>setEvent({...event,description:v})}/><Field label="Location" value={event.location} onChange={(v:any)=>setEvent({...event,location:v})}/><div className="grid grid-cols-2 gap-3"><Field label="Starts" type="datetime-local" value={event.startAt} onChange={(v:any)=>setEvent({...event,startAt:v})}/><Field label="Ends" type="datetime-local" value={event.endAt} onChange={(v:any)=>setEvent({...event,endAt:v})}/></div><button disabled={!event.title} onClick={()=>void institutionStudioApi.createEvent({...event,startAt:new Date(event.startAt).toISOString(),endAt:new Date(event.endAt).toISOString()}).then(()=>{setEvent({...event,title:"",description:"",location:""});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Create event</button></FormCard></div>
    <div className="grid gap-5 2xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Opportunities</h2><p className="mt-1 text-xs text-slate-500">Internships, placements, scholarships, competitions and projects.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-500"><th className="pb-3">Opportunity</th><th className="pb-3">Type</th><th className="pb-3">Deadline</th><th className="pb-3">Status</th><th/></tr></thead><tbody>{opportunities.map((o:any)=><tr key={o.id} className="border-b border-slate-50"><td className="py-3"><div className="font-bold">{o.title}</div><div className="text-xs text-slate-500">{o.organization||o.location||"Campus opportunity"}</div></td><td className="py-3 capitalize">{o.kind}</td><td className="py-3">{o.deadline?new Date(o.deadline).toLocaleDateString():"—"}</td><td className="py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{o.status}</span></td><td className="py-3 text-right"><button onClick={()=>void institutionStudioApi.archiveOpportunity(o.id).then(reload)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!opportunities.length?<Empty text="No opportunities yet."/>:null}</div></section>
      <FormCard title="Add Opportunity" icon={ShieldCheck}><Select label="Type" value={opp.kind} onChange={(v:any)=>setOpp({...opp,kind:v})} options={["internship","placement","part_time","project","scholarship","competition"].map(v=>({value:v,label:v.replace("_"," ")}))}/><Field label="Title" value={opp.title} onChange={(v:any)=>setOpp({...opp,title:v})}/><Field label="Organization" value={opp.organization} onChange={(v:any)=>setOpp({...opp,organization:v})}/><TextArea label="Description" value={opp.description} onChange={(v:any)=>setOpp({...opp,description:v})}/><Field label="Location" value={opp.location} onChange={(v:any)=>setOpp({...opp,location:v})}/><Field label="Apply URL" value={opp.applyUrl} onChange={(v:any)=>setOpp({...opp,applyUrl:v})}/><Field label="Deadline" type="datetime-local" value={opp.deadline} onChange={(v:any)=>setOpp({...opp,deadline:v})}/><button disabled={!opp.title} onClick={()=>void institutionStudioApi.createOpportunity({...opp,deadline:opp.deadline?new Date(opp.deadline).toISOString():null}).then(()=>{setOpp({kind:"internship",title:"",organization:"",description:"",location:"",applyUrl:"",deadline:""});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Add opportunity</button></FormCard></div>
  </div>;
}

function People({ approvals, staff, roles, departments, reload, setNotice }: any) {
  const [newStaff,setNewStaff]=useState<any>({name:"",email:"",phone:"",title:"",departmentId:"",roleId:"",status:"active"});
  const [newRole,setNewRole]=useState<any>({name:"",description:"",permissions:["events.manage","analytics.view"]});
  return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Student Approval Queue</h2><p className="mt-1 text-xs text-slate-500">Verify students before they enter the institution community.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-700">{approvals.length} pending</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-500"><th className="pb-3">Student</th><th className="pb-3">Program / Department</th><th className="pb-3">Source</th><th className="pb-3">Status</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{approvals.map((a:any)=><tr key={a.id} className="border-b border-slate-50"><td className="py-3"><div className="font-bold">{a.user?.name||a.user?.handle||a.user_id}</div><div className="text-xs text-slate-500">{a.user?.course||a.user?.city||"Student"}</div></td><td className="py-3 text-slate-600">{a.verification_data?.department||a.verification_data?.course||"—"}</td><td className="py-3 text-slate-600">{a.source||"application"}</td><td className="py-3"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{a.status}</span></td><td className="py-3"><div className="flex justify-end gap-2"><button onClick={()=>void institutionStudioApi.decideStudent(a.id,"approved","Approved by institution administrator").then(reload)} className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Check className="h-4 w-4"/></button><button onClick={()=>void institutionStudioApi.decideStudent(a.id,"rejected","Rejected by institution administrator").then(reload)} className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-700"><X className="h-4 w-4"/></button></div></td></tr>)}</tbody></table>{!approvals.length?<Empty text="No students are waiting for approval."/>:null}</div></section>
    <div className="grid gap-5 2xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Faculty & Staff</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{staff.map((s:any)=><div key={s.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-blue-50 text-blue-600"><Users className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{s.name}</div><div className="truncate text-xs text-slate-500">{s.title||s.email||"Staff"}</div></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${s.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{s.status}</span></div><div className="mt-3 text-xs text-slate-500">{departments.find((d:any)=>d.id===s.department_id)?.name||"No department"} · {roles.find((r:any)=>r.id===s.role_id)?.name||"No custom role"}</div></div>)}</div></section><FormCard title="Add Faculty / Staff" icon={UserCheck}><Field label="Name" value={newStaff.name} onChange={(v:any)=>setNewStaff({...newStaff,name:v})}/><Field label="Email" type="email" value={newStaff.email} onChange={(v:any)=>setNewStaff({...newStaff,email:v})}/><Field label="Phone" value={newStaff.phone} onChange={(v:any)=>setNewStaff({...newStaff,phone:v})}/><Field label="Title" value={newStaff.title} onChange={(v:any)=>setNewStaff({...newStaff,title:v})}/><Select label="Department" value={newStaff.departmentId} onChange={(v:any)=>setNewStaff({...newStaff,departmentId:v})} options={[{value:"",label:"None"},...departments.map((d:any)=>({value:d.id,label:d.name}))]}/><Select label="Role" value={newStaff.roleId} onChange={(v:any)=>setNewStaff({...newStaff,roleId:v})} options={[{value:"",label:"None"},...roles.map((r:any)=>({value:r.id,label:r.name}))]}/><button disabled={!newStaff.name} onClick={()=>void institutionStudioApi.createStaff(newStaff).then(()=>{setNewStaff({name:"",email:"",phone:"",title:"",departmentId:"",roleId:"",status:"active"});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Add staff member</button></FormCard></div>
    <div className="grid gap-5 2xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Roles & Permissions</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{roles.map((r:any)=><div key={r.id} className="rounded-2xl border border-slate-200 p-4"><div className="font-bold">{r.name}</div><div className="mt-1 text-xs text-slate-500">{r.description||"Custom institution role"}</div><div className="mt-3 flex flex-wrap gap-1">{(r.permissions||[]).slice(0,5).map((p:string)=><span key={p} className="rounded-md bg-slate-100 px-1.5 py-1 text-[10px] font-semibold text-slate-600">{p}</span>)}</div></div>)}</div></section><FormCard title="Create Role" icon={ShieldCheck}><Field label="Role name" value={newRole.name} onChange={(v:any)=>setNewRole({...newRole,name:v})}/><TextArea label="Description" value={newRole.description} onChange={(v:any)=>setNewRole({...newRole,description:v})}/><TextArea label="Permissions (comma separated)" value={newRole.permissions.join(", ")} onChange={(v:any)=>setNewRole({...newRole,permissions:v.split(",").map((x:string)=>x.trim()).filter(Boolean)})}/><button disabled={!newRole.name} onClick={()=>void institutionStudioApi.createRole(newRole).then(()=>{setNewRole({name:"",description:"",permissions:["events.manage","analytics.view"]});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Create role</button></FormCard></div>
  </div>;
}

function CampusPlaces({ places, reload, setNotice }: any) {
  const [draft,setDraft]=useState<any>({name:"",category:"building",description:"",latitude:"",longitude:"",floor:""});
  return <div className="grid gap-5 2xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Campus Map & Facilities</h2><p className="mt-1 text-xs text-slate-500">Buildings, departments, labs, library, hostel, sports, cafeteria and emergency points.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{places.map((p:any)=><div key={p.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><MapPin className="h-5 w-5"/></div><button onClick={()=>void institutionStudioApi.deleteStudioPlace(p.id).then(reload)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 font-bold">{p.name}</div><div className="mt-1 text-xs capitalize text-slate-500">{p.category}{p.floor?` · ${p.floor}`:""}</div><div className="mt-2 text-xs text-slate-500">{p.description||`${p.latitude}, ${p.longitude}`}</div></div>)}</div>{!places.length?<Empty text="No campus places published."/>:null}</section><FormCard title="Add Campus Place" icon={MapPin}><Field label="Name" value={draft.name} onChange={(v:any)=>setDraft({...draft,name:v})}/><Field label="Category" value={draft.category} onChange={(v:any)=>setDraft({...draft,category:v})}/><TextArea label="Description" value={draft.description} onChange={(v:any)=>setDraft({...draft,description:v})}/><div className="grid grid-cols-2 gap-3"><Field label="Latitude" type="number" value={draft.latitude} onChange={(v:any)=>setDraft({...draft,latitude:v})}/><Field label="Longitude" type="number" value={draft.longitude} onChange={(v:any)=>setDraft({...draft,longitude:v})}/></div><Field label="Floor / area" value={draft.floor} onChange={(v:any)=>setDraft({...draft,floor:v})}/><button disabled={!draft.name||!draft.latitude||!draft.longitude} onClick={()=>void institutionStudioApi.createPlace({...draft,latitude:Number(draft.latitude),longitude:Number(draft.longitude)}).then(()=>{setDraft({name:"",category:"building",description:"",latitude:"",longitude:"",floor:""});return reload();}).catch((e:any)=>setNotice(e.message))} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Add place</button></FormCard></div>;
}

function FormCard({ title, icon: Icon, children }: any) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-5 w-5"/></div><h2 className="font-black">{title}</h2></div><div className="mt-5 space-y-3">{children}</div></section>; }
function Field({ label, value, onChange, type="text" }: any) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><input type={type} value={value??""} onChange={(e)=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-50"/></label>; }
function TextArea({ label, value, onChange }: any) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><textarea rows={3} value={value??""} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-50"/></label>; }
function Select({ label, value, onChange, options }: any) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><select value={value??""} onChange={(e)=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500">{options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function Empty({ text }: { text:string }) { return <div className="mt-4 rounded-xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-400">{text}</div>; }
